### ISSUE TITLE
Installation Bug Report: Plugin Error while installation 

### ISSUE THREAD

**Issue by makamkkumar** [deepbands/buildseg#5]
An error occurred during execution of following code:
pyplugin_installer.instance().installPlugin('buildseg', stable=False)

Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/share/qgis/python/pyplugin_installer/installer.py", line 333, in installPlugin
    self.processDependencies(plugin["id"])
  File "/usr/share/qgis/python/pyplugin_installer/installer.py", line 682, in processDependencies
    dlg = QgsPluginDependenciesDialog(plugin_id, to_install, to_upgrade, not_found)
  File "/usr/share/qgis/python/pyplugin_installer/qgsplugindependenciesdialog.py", line 92, in __init__
    _make_row(data, i, name)
  File "/usr/share/qgis/python/pyplugin_installer/qgsplugindependenciesdialog.py", line 63, in _make_row
    widget.use_stable_version = data['use_stable_version']
KeyError: 'use_stable_version'

Python version:
3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]

QGIS version:
3.22.3-Białowieża 'Białowieża', 1628765ec7

Python path:
['/usr/share/qgis/python', '/home/robotics/.local/share/QGIS/QGIS3/profiles/default/python', '/home/robotics/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/robotics/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages', '/home/robotics/.local/share/QGIS/QGIS3/profiles/default/python', '/home/robotics/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DeepLearningTools']

**Comment by yharby** [comment]
We are working on that in the new version, thank you!

**Comment by yharby** [comment]
@makamkkumar 
New Stable Version released yesterday with fixes #8, you can upgrade directly from QGIS
https://plugins.qgis.org/plugins/buildseg/
